name: Generate flatmap with mapmaker

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: 'ZIP file URL containing the flatmap data'
        required: true
        type: string
        default: 'https://github.com/hsorby/run-flatmap-maker/releases/download/input/rcl_circuit.zip'

jobs:
  generate-flatmap:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          path: mapmaker
          repository: AnatomicMaps/flatmap-maker

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Ubuntu packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libfontconfig1 libegl1 libglx-mesa0 libgl1-mesa-dri

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          activate-environment: true

      - name: Install dependencies
        run: |
          cd mapmaker
          uv sync
          pip install .

      - name: Download zip
        run: |
          curl -L "${{ github.event.inputs.zip_url }}" -o file.zip
          unzip file.zip

      - name: Run mapmaker
        run: |
          mapmaker \
            --output ./flatmaps \
            --source . \
            --commit production \
            --manifest manifest.json \
            --force \
            --silent --log mapmaker.log \
            --no-path-layout \
            --ignore-git \
            --background-tiles
        env:
          SCICRUNCH_API_KEY: ${{ secrets.SCICRUNCH_API_KEY }}

      - name: Upload flatmaps
        uses: actions/upload-artifact@v7
        with:
          name: flatmaps
          path: flatmaps

      - name: Upload log
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: mapmaker-log
          path: mapmaker.log
